version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_docker
    ports:
      - "2345:5432"
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_docker
    env_file:
      - .env
    ports:
      - "7777:8000"
    depends_on:
      - db
    command: gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
